openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    fhdv
  version: 1.0.11
servers:
  - url: http://localhost:8080/api/v3
tags:
  - name: project
    description: Everything about your projects
paths:
  /projects:
    get:
      tags:
        - project
      summary: Get list of all projects
      description: Get list of all projects
      operationId: getProjects
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
        '404':
          description: Projects not found
components:
  schemas:
    Project:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Project1
        description:
          type: string
          example: This is a description.
        isWork:
          type: boolean
          example: true