CREATE TABLE external_project_mapping (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id              BIGINT NOT NULL,
    external_project_data   CLOB NOT NULL,

    PRIMARY KEY (id),
    FOREIGN KEY (project_id) REFERENCES Project(id) ON DELETE CASCADE
);