CREATE TABLE IF NOT EXISTS  external_project_mapping (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id              BIGINT NOT NULL,

    external_system_id      VARCHAR NOT NULL,

    external_project_name   VARCHAR NOT NULL,
    external_task_id        BIGINT NOT NULL,
    external_task_name      VARCHAR NOT NULL,
    external_task_metadata  CLOB NOT NULL,

    PRIMARY KEY (id),
    FOREIGN KEY (project_id) REFERENCES Project(id) ON DELETE CASCADE
);